<html>
<head>
	<title></title>
</head>
<body>
<h1 style="text-align: center;line-height: 120%;">ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ВЫСШЕГО ОБРАЗОВАНИЯ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ УНИВЕРСИТЕТ «МОСКОВСКИЙ ЭНЕРГЕТИЧЕСКИЙ ИНСТИТУТ» Кафедра «РЗиАЭ»</h1>
<h2 style="text-align: center;line-height: 20%;">Лабораторная работа №1</h2>

<h3 style="text-align: center;line-height: 80%;"><em>Симплекс-метод</em></h3>

<p style="text-align: right;line-height: 40%;">Выполнил: студент группы Э-13м-21</p>
<p style="text-align: right;line-height: 40%;">Груздов А.Г.</p>

<p style="text-align: right;line-height: 40%;">Принял: Рогозинников Е.И.</p>
<h4 style="text-align: center;line-height: 100%;"><em> Москва, 2022</em></h3>
</body>
</html>

In [241]:
import numpy as np
import math
from scipy import optimize


In [242]:
#-------------------------- -------------------------- #
lim = "max"
if lim == "max":
    M = -1j # Число М
else:
    M = 1j
# #-------------------------- -------------------------- #
# Zx = [4, -4, 1]
# A = [[4, 5, 4], [0, 1, 0]] # [Свободные члены системы ограничений (правая часть)],[где {0 - =} , {1 - ≥} , {-1 - ≤}]
# m = len(Zx) # Количество ограничений (количество строк)
# n = len(Zx) # Количество переменных (без учёта балансовых и M переменных)
# basis = []
#
# a = [-4,-3, 0]# Коэффициенты при переменных в первом ограничении
# b = [ 4, 4, 0]# Коэффициенты при переменных во втором ограничении
# c = [ 4, 3, 1]# Коэффициенты при переменных в третьем ограничении
# source_in = np.zeros((m,n))
# source_in[0] = a
# source_in[1] = b
# source_in[2] = c
#
# for i in range(0,m):
#     if A[0][i] < 0: # Если элементы правой части отрицательные, то сменим знак
#         if A[0][i] == 1 or A[0][i] == -1:
#             (-1)*A[0][i] #
#             (-1)*A[1][i] # меняем сам знак на противоположный
#             (-1)*source_in[i] # меняем знаки в ограничениях в левой части на противоположные
#         else:
#             (-1)*A[0][i]
#             (-1)*source_in[i]
# new_n = n # столбец с 0
# print("Проверка на предпочтительный вид")
# if 1 in source_in:
#     for k in range(0, n): # порядок ограничений в левой части
#         for t in range(0, m):
#             if source_in[:,k][t] == 1:
#                 basis.append(t)
#                 print(f"В {1+k} уравнение со знаком [=] выбрана в качестве базисной переменной значение под индексом {t}. Уравнение имеет предпочтительный вид. ")
#     for j in range(0,m):
#         if A[1][j] == 0:
#             if 1 not in source_in[j]:
#                 Zx.append(M)
#                 X0 = np.zeros((new_n,1))
#                 source_in = np.hstack((source_in,X0))
#                 basis.append(new_n)
#                 source_in[j][new_n] = 1
#                 print(f"В {j+1} уравнение со знаком [=] добавилась базисная пременная {M} индекс {new_n}")
# for j in range(0, m): # порядок ограничений в правой части
#     if A[1][j] == 1:
#         if 1 not in source_in[j]:
#             Zx.append(0)
#             X0 = np.zeros((new_n,1))
#             source_in = np.hstack((source_in,X0))
#             source_in[j][new_n] = -1
#             Zx.append(M)
#             X0 = np.zeros((new_n,1))
#             source_in = np.hstack((source_in,X0))
#             source_in[j][new_n] = 1
#             basis.append(j)
#             print(f"В {j+1} уравнение со знаком [≥] добавилась базисная пременная {M} индекс {5} ")
#     if A[1][j] == -1:
#         if 1 not in source_in[j]:
#             new_n +=1
#             Zx.append(0)
#             X0 = np.zeros((new_n,1))
#             new_source_in = np.hstack((source_in,X0))
#             new_source_in[j][new_n] = 1
#             basis.append(1)
#             new_n +=1
#             print(f"В {j+1} уравнение со знаком [≤] добавилась базисная пременная {M} индекс {new_n} ")
# basis = [2,3,5]
# print(new_source_in, basis, Zx)
# A0 = A[0]
# Zx_M = Zx
# Cb = [M, M, 1]
#
# w = 2 # Количество искусственных базисных переменных
# m = len(Cb) # Количество ограничений (количество строк)
# l = len(Zx_M) # Количество переменных в М задаче (количество столбцов)
# n = l-m+1 # Количество переменных (количество столбцов без М переменных)
# quantity_x = [0,1,2]

In [ ]:
# #-------------------------- -------------------------- #
# #-------------------------- -------------------------- #
# basis =[           5,    3, 6] # Порядковые номера базисных переменных (нумерация с 0)
# Zx_M = [-3, 1, -1, 0, 0, M, M] # Коэффициенты при переменных в целевой функции М задачи
# A0 = [0,
#       6,
#       6] # Свободные члены системы ограничений
# Cb = [M,
#       0,
#       M] # Коэффициенты при базисных переменных в целевой функции исходной задач
# #-------------------------- -------------------------- #
#
# #-------------------------- -------------------------- #
# w = 2 # Количество искусственных базисных переменных
# m = len(Cb) # Количество ограничений (количество строк)
# l = len(Zx_M) # Количество переменных в М задаче (количество столбцов)
# n = l-m+1 # Количество переменных (количество столбцов без М переменных)
# #-------------------------- -------------------------- #
#
# #--------------------------Ограничения -------------------------- #
#
# a = [2, -1, -2, 0, 0, 1, 0]# Коэффициенты при переменных в первом ограничении
# b = [ 2, 1, 4, 1, 0, 0, 0]# Коэффициенты при переменных во втором ограничении
# c = [-3, 4, 4, 0, -1, 0, 1]# Коэффициенты при переменных в третьем ограничении
#
# source_M = np.zeros((m,l)) # Пустая матрица размером m, l для заполнения коэффициентами при переменных из системы ограничений
# source_M[0] = a # Первая строка матрицы
# source_M[1] = b # Вторая строка матрицы
# source_M[2] = c # Третья строка матрицы
# #-------------------------- -------------------------- #
#
# #--------------------------Ограничении исходной задачи -------------------------- #
# source = source_M[:,0:4]
# #-------------------------- -------------------------- #
# print(source)
# print()

In [243]:
lim = "max"
if lim == "max":
    M = -1j # Число М
else:
    M = 1j
#-------------------------- -------------------------- #
basis =[       2,    4, 5] # Порядковые номера базисных переменных (нумерация с 0)
Zx_M = [4, -4, 1, 0, M, M] # Коэффициенты при переменных в целевой функции М задачи
A0 = [4,
      4,
      5] # Свободные члены системы ограничений
Cb = [M,
      M,
      1] # Коэффициенты при базисных переменных в целевой функции исходной задач
#-------------------------- -------------------------- #

#-------------------------- -------------------------- #
w = 2 # Количество искусственных базисных переменных
m = len(Cb) # Количество ограничений (количество строк)
l = len(Zx_M) # Количество переменных в М задаче (количество столбцов)
n = l-m+1 # Количество переменных (количество столбцов без М переменных)
#-------------------------- -------------------------- #
quantity_x = [0,1,2]
#--------------------------Ограничения -------------------------- #

a = [-4,-3, 0,  0,  1,  0]# Коэффициенты при переменных в первом ограничении
b = [ 4, 4, 0, -1,  0,  1]# Коэффициенты при переменных во втором ограничении
c = [ 4, 3, 1,  0,  0,  0]# Коэффициенты при переменных в третьем ограничении


source_M = np.zeros((m,l)) # Пустая матрица размером m, l для заполнения коэффициентами при переменных из системы ограничений
source_M[0] = a # Первая строка матрицы
source_M[1] = b # Вторая строка матрицы
source_M[2] = c # Третья строка матрицы
#-------------------------- -------------------------- #

#--------------------------Ограничении исходной задачи -------------------------- #


In [244]:
def mark_1(array_f):
    """
    @:doc "Признак бесконечности множества оптимальных планов (альтернативный оптимум) - если в индексной строке содержащей оптимальный
     план) имеется хотя бы одна нулевая оценка, соответствующая свободной переменной, то задача линейного программирования имеет
     бесконечное множество оптимальных планов.
     ========================================================
    """
    for i in range(0, len(quantity_x)):
        if array_f[quantity_x[i]] == 0:
            print("Признак бесконечности множества оптимальных планов (альтернативный оптимум)")

In [245]:
def mark_2(ai0j):
    """
    @:doc "Признак неограниченности целевой функции:: если в оптимальном плане М-задачи
    не все искусственные переменные равны нулю, то система ограничений исходной задачи не-совместна."
     ========================================================
    """
    flag = True
    for j in range(0,m):
        count = 0
        if ai0j[j] < 0 :
            count+=1
        if count == l-w:
            print(f"Признак неограниченности целевой функции. Все переменные в разрешающем столбце отрицательные {ai0j}")
            flag = False
        else:
            0
    return flag


In [246]:
def mark_3(source_M, Cb, Zx):
    """
    @:doc "Признак несовместности системы ограничений: если в разрешающем столбце все переменные отрицательные"
     ========================================================
    """
    for j in range(0,m):
        count = 0
        for i in range(0,l):
            if Cb[j] == M and Zx[i] != M:
                    value = source_M[:,i][j]
                    if value <= 0:
                        count+=1
        if count == l-w:
            print(f"Признак несовместности системы ограничений. Невозможно вывести искусственную переменную из базиса под индексом {j}.")
            flag = False
        else:
            0
    return flag

In [247]:
def deltaFj(M_or_NotM:bool,Zx, Cb, source_M):
    """
    @:doc Функция отвечающая за расчет оценночной строки для основной и М задачи. Параметр M_or_NotM отвечает за выбор типа функции
     ========================================================
    @:arg M_or_NotM:bool - False- оценочной строка для M задачи, a True для основной
    @:arg: Zx_M:list: Коэффициенты при переменных Z(x)
    @:arg: source_M матрица с коэффициентами системы ограничений
    """
    #print_f_0 = " + "
    f = [] # Заполнение оценочной строки "0"
    for i in range(0,l):
        f.append(0)
        for j in range(0,m):
            if M_or_NotM: # условие для проверки типа оценочной строки для М и не М задачи
                if Cb[j] != M: # # оценочная строка с учетом искуственных переменных при БП содержащие искуственные переменные
                    f[i] += Cb[j]*source_M[:,i][j]
                    #print_f_0 += " "+'{}*{}'.format(Cb[j], source_M[:,i][j])
            else:
                if Cb[j] == M:# оценочная строка с учетом искуственных переменных
                    f[i] += (Cb[j]*source_M[:,i][j]).imag
        #print(print_f_0 + " = {}".format(f[i]))
        if M_or_NotM: # Теперь следует вычесть коэффиицены при Z(x) не содержащие\содержащие  искуственные переменные
            if Zx[i] != M:
                f[i] -= Zx[i]
        else:
            if Zx[i] == M:
                f[i] -= (Zx[i]).imag
    print("Оценночная строка fj-cj: ",f) if M_or_NotM else print("Оценночная строка fj-cj M задачи: ",f)
    return f

In [248]:
def validate_Optim(array_f,array_f_M):
    """
    @:doc Функция определяет оптимальность найденного плана
    ========================================================
    @:arg array_f - оценочная строка основной задачи
    @:arg array_f_M - оценочная строка M задачи
    """
    if lim == "max":
        if min(array_f_M)<0 or min(array_f)<0 :
           print("План не оптимален, следует перейти к \"нехудшему\" решению.")
           flag = True
        else:
            print("План оптимален.")
            mark_1(array_f) #Проверка на Признак бесконечности множества оптимальных планов (альтернативный оптимум)
            flag = False
    else:
        if min(array_f_M)>0 or min(array_f)>0 :
           print("План не оптимален, следует перейти к \"нехудшему\" решению.")
           flag = True
        else:
            print("План оптимален.")
            mark_1(array_f) #Проверка на Признак бесконечности множества оптимальных планов (альтернативный оптимум)
            flag = False
    return flag

In [249]:
def optim_iColums_f_orf_M(array):
    """
    @:doc Функция определяет СТОЛБЦЫ в оценночной строке со значениями удовлетворяющие условию min(|deltaF|) --> max, max(|deltaF|) --> min
    ========================================================
    @:arg array_f - оценочная строка
    return
        @:arg optim - оптимальное значение столбца
        @:arg list_null - Имеется ввиду, что если нету отрицательных элементов для max, то True
    """
    if lim == "max":
        index_optim_colums = [i for i,num  in enumerate(array) if num < 0]# Массив с индексами удовлетворяющий условию MAX
        value_optim_colums = [array[i] for i in index_optim_colums]
        if len(index_optim_colums) == 0:
            optim = None
        else:
            optim = min(value_optim_colums)
    else:
        index_optim_colums = [i for i,num  in enumerate(array) if num > 0]# Массив с индексами удовлетворяющий условию MIN
        value_optim_colums = [array[i] for i in index_optim_colums]
        if len(index_optim_colums) == 0:
            optim = None
        else:
            optim = max(value_optim_colums)

    return optim


In [250]:
def validate_iСolumn(array_f,array_f_M,optim_iСolumn_f,optim_iСolumn_f_M, source_M):
    """
    @:doc Функция определяет разрешающий СТОЛБЕЦ! Удовлетворяющий условию min(|deltaF|) --> max, max(|deltaF|) --> min
    ========================================================
    @:arg optim_iСolumn_f \..._f_M - возможный оптимальное значение в оценочной строки разрешающего столбца
    return
        @:arg iСolumn - индекс разрешающего столбца
        @:arg ai0j - массив с разрешащим столбцом
    """
    if lim == "max":
        if optim_iСolumn_f == None:
            iСolumn = list(array_f_M).index(optim_iСolumn_f_M)
        elif optim_iСolumn_f_M == None:
            iСolumn = list(array_f).index(optim_iСolumn_f)
        elif optim_iСolumn_f < optim_iСolumn_f_M:
            iСolumn = list(array_f).index(optim_iСolumn_f)
        else:
            iСolumn = list(array_f_M).index(optim_iСolumn_f_M)
    else:
        if optim_iСolumn_f == None:
            iСolumn = list(array_f_M).index(optim_iСolumn_f_M)
        elif optim_iСolumn_f_M == None:
            iСolumn = list(array_f).index(optim_iСolumn_f)
        elif optim_iСolumn_f > optim_iСolumn_f_M:
            iСolumn = list(array_f).index(optim_iСolumn_f)
        else:
            iСolumn = list(array_f_M).index(optim_iСolumn_f_M)
    ai0j = [source_M[:,iСolumn][j] for j in range(0,m)]
    flag = mark_2(ai0j)
    return flag, iСolumn, ai0j

In [251]:
def validate_jRow_ai0j0(iСolumn, ai0j, source_M, A0):
    """
    @:doc Функция определяет оптимальное {Θ}, а также определяет
    ========================================================
    @:arg array_f - оценочная строка основной задачи
    @:arg teta - массив с элементами
    return
        @:arg jRow - индекс разрешащей строки
        @:arg aij0 - массив с разрешащей строкой
        @:arg aij - оценочная строка M задачи
        or teta_i == math.isnan(float('nan')) or teta_i == math.isinf(float('inf'))
    """
    teta = np.zeros((m))

    for i  in range(0,m): # Расчёт {Θ} Если элементы отрицательные, то вернуть "прочерк" --> "-1"
        teta_i = round(A0[i]/ai0j[i],2)
        if teta_i <= 0:
            teta_i = -1
        teta[i] = teta_i

    index_optim_teta= [i for i,num  in enumerate(teta) if num > 0 ]# Массив с индексами удовлетворяющей условию
    value_optim_colums = [teta[i] for i in index_optim_teta]
    jRow = list(teta).index(min(value_optim_colums))
    aij0 = [source_M[:,i][jRow] for i in range(0,l)]
    ai0j0 = source_M[:,iСolumn][jRow]
    print("Элементы массива teta ~ Θ")
    [print(f'Θ_{i}j = ({A0[i]})/({ai0j[i]}) = {teta[i]}') for i  in range(0,m)]
    print(f"Индекс разрешающего столбца: [{iСolumn}]")
    print(f"Элементы разрешающего столбца: [ {ai0j}]")
    print(f"Индекс разрешающей строки: [{jRow}]")
    print(f"Элементы разрешающей строки: [{aij0}]")
    print(f"Разрешающий элемент: [{ai0j0}]")
    return jRow, aij0, ai0j0

In [252]:
def new_simplex_table(iСolumn, ai0j, jRow, aij0, ai0j0, source_M, A0, Cb, Zx_M, basis):
    new_A0 = np.zeros((m))
    new_source_M = source_M.copy()
    Zx_M_new = Zx_M.copy()
    for i in range(0,l):
        if i != iСolumn:
            for j in range(0,m):
                if j != jRow:
                    new_A0[j] = A0[j] - (A0[jRow]*ai0j[j])/ai0j0
                    new_source_M[:,i][j] = source_M[:,i][j] - (ai0j[j]*aij0[i])/ai0j0
                    source_M[:,iСolumn][j] = 0
                else:
                    new_A0[j] = A0[j]/ai0j0
                    new_source_M[:,i][j] = aij0[i]/ai0j0
    for j in range(0,m):
        for i in range(0,l):
           if basis[jRow] == i:
               if Zx_M_new[i] == M:
                   new_source_M[:,i][j] = 0
           if jRow != j:
               new_source_M[:,iСolumn][j] = 0

    new_source_M[:,iСolumn][jRow] = 1
    Cb[jRow] = Zx_M[iСolumn]
    Zx_M_new[basis[jRow]] = 0
    basis[jRow] = Zx_M.index(Zx_M[iСolumn])

    print("Новая симплекс таблица: ")
    print(new_source_M)
    print("Свободные члены системы ограничений Aо: ", new_A0)
    print("Индексы элементов нового базиса: ", basis)
    print("Коэффициенты при базисных переменных: ", Cb)
    print("Коэффициенты новой целевой функции ", Zx_M_new)
    return new_source_M, new_A0, basis, Cb , Zx_M_new

In [253]:
def result(basis,A0,Cb):
    result = [0 for i in range(0,n)] # Заполнение нулями по количеству переменных
    for i in range(m):
        result[basis[i]] = A0[i] # Заполнение оптимального плана значениями А0
    print("\nresult = ", result)
    # Расчет минимального/максимального значения целевой функции
    z = 0
    for i in range(m):
        z += Cb[i] * A0[i]
    print("\nz = ", z)

In [254]:
print(f"Задача на: {lim} Z(x)")
print("  х1,...,хn,w1,...,wn")
print(" ",Zx_M)
print(source_M)
flag = True
iteration = 0
print()
print(f"=========================Итерация [{iteration}]=========================" )
print()
#flag = mark_3(source_M, Cb, Zx_M)
if flag:
    array_f = deltaFj(True, Zx_M, Cb, source_M)
    array_f_M = deltaFj(False, Zx_M, Cb, source_M)
    flag = validate_Optim(array_f,array_f_M)
    optim_iСolumn_f_M = optim_iColums_f_orf_M(array_f_M)
    optim_iСolumn_f = optim_iColums_f_orf_M(array_f)
    flag, iСolumn, ai0j = validate_iСolumn(array_f,array_f_M,optim_iСolumn_f,optim_iСolumn_f_M, source_M)
    jRow, aij0, ai0j0 = validate_jRow_ai0j0(iСolumn, ai0j, source_M, A0)
    source_M, new_A0, basis, Cb, Zx_M_new = new_simplex_table(iСolumn, ai0j, jRow, aij0, ai0j0, source_M, A0, Cb, Zx_M, basis)
    flag = mark_3(source_M, Cb, Zx_M)
while(flag):
    iteration += 1
    print()
    print(f"=========================Итерация [{iteration}]=========================" )
    print()
    array_f = deltaFj(True, Zx_M_new, Cb, source_M)
    array_f_M = deltaFj(False, Zx_M_new, Cb, source_M)

    flag = validate_Optim(array_f,array_f_M)

    optim_iСolumn_f_M = optim_iColums_f_orf_M(array_f_M)
    optim_iСolumn_f = optim_iColums_f_orf_M(array_f)
    flag, iСolumn, ai0j = validate_iСolumn(array_f,array_f_M,optim_iСolumn_f,optim_iСolumn_f_M, source_M)
    jRow, aij0, ai0j0 = validate_jRow_ai0j0(iСolumn, ai0j, source_M, new_A0)

    source_M, new_A0, basis, Cb, Zx_M_new = new_simplex_table(iСolumn, ai0j, jRow, aij0, ai0j0, source_M, new_A0, Cb, Zx_M, basis)
    flag = mark_3(source_M, Cb, Zx_M)
result(basis,new_A0,Cb)


Задача на: max Z(x)
  х1,...,хn,w1,...,wn
  [4, -4, 1, 0, (-0-1j), (-0-1j)]
[[-4. -3.  0.  0.  1.  0.]
 [ 4.  4.  0. -1.  0.  1.]
 [ 4.  3.  1.  0.  0.  0.]]

=========================Итерация [0]=========================

Оценночная строка fj-cj:  [0.0, 7.0, 0.0, 0.0, 0.0, 0.0]
Оценночная строка fj-cj M задачи:  [0.0, -1.0, 0.0, 1.0, 0.0, 0.0]
План не оптимален, следует перейти к "нехудшему" решению.
Элементы массива teta ~ Θ
Θ_0j = (4)/(-3.0) = -1.0
Θ_1j = (4)/(4.0) = 1.0
Θ_2j = (5)/(3.0) = 1.67
Индекс разрешающего столбца: [1]
Элементы разрешающего столбца: [ [-3.0, 4.0, 3.0]]
Индекс разрешающей строки: [1]
Элементы разрешающей строки: [[4.0, 4.0, 0.0, -1.0, 0.0, 1.0]]
Разрешающий элемент: [4.0]
Новая симплекс таблица: 
[[-1.    0.    0.   -0.75  0.    0.75]
 [ 1.    1.    0.   -0.25  0.    0.25]
 [ 1.    0.    1.    0.75  0.   -0.75]]
Свободные члены системы ограничений Aо:  [7. 1. 2.]
Индексы элементов нового базиса:  [2, 1, 5]
Коэффициенты при базисных переменных:  [(-0-1j), -4, 

IndexError: list assignment index out of range

In [ ]:
targetFunctionCoef = [4, -4, 1] # Коэффициенты при переменных в целевой функции

leftPartLimitIneq = [[4, 4, 0]]  # Левые части неравенств в системе ограничений
rightPartLimitIneq = [4] # Правые части неравенств в системе ограничений

leftPartLimitEq = [[-4, -3, 0],[4, 3, 1]] # Левые части равенств в системе ограничений
rightPartLimitEq = [4,5] # Правые части равенств в системе ограничений

# Применение функции для получения результатов
opt = optimize.linprog(c=targetFunctionCoef,
                       A_ub=leftPartLimitIneq,
                       b_ub=rightPartLimitIneq,
                       A_eq=leftPartLimitEq,
                       b_eq=rightPartLimitEq,
                       method="revised simplex")
# Вывод результатов в консоль
print('\nРасчет с помощью метода linprog из библиотеки Scipy \n', opt)

In [ ]:
# print(source_M)
# array_f = deltaFj(True, Zx_M, Cb, source_M)
# array_f_M = deltaFj(False, Zx_M, Cb, source_M)
# flag = validate_Optim(array_f,array_f_M)
# optim_iСolumn_f_M = optim_iColums_f_orf_M(array_f_M)
# optim_iСolumn_f = optim_iColums_f_orf_M(array_f)
# iСolumn, ai0j = validate_iСolumn(array_f,array_f_M,optim_iСolumn_f,optim_iСolumn_f_M, source_M)
# jRow, aij0, ai0j0 = validate_jRow_ai0j0(iСolumn, ai0j, source_M, A0)
# new_A0 = np.zeros((m))
# new_source_M = source_M.copy()
# for i in range(0,l):
#     if i != iСolumn:
#         for j in range(0,m):
#             if j != jRow:
#                 new_A0[j] = A0[j] - (A0[jRow]*ai0j[j])/ai0j0
#                 new_source_M[:,i][j] = source_M[:,i][j] - (ai0j[j]*aij0[i])/ai0j0
#             else:
#                 new_A0[j] = A0[j]/ai0j0
#                 new_source_M[:,i][j] = aij0[i]/ai0j0
# for j in range(0,m):
#     for i in range(0,l):
#        if basis[jRow] == i:
#             new_source_M[:,i][j] = 0
#        if jRow != j:
#            new_source_M[:,iСolumn][j] = 0
#
# new_source_M[:,iСolumn][jRow] = 1
# Cb[jRow] = Zx_M[iСolumn]
# Zx_M_new = Zx_M.copy()
# Zx_M_new[basis[jRow]] = 0
#
#
# new_source_M, new_A0, Zx_M_new